---
# restart mysql

- name: start mysql 
  command: /etc/init.d/mysql start 

- name: restart mysql 
  command:  /etc/init.d/mysql restart 

- name: stop mysql 
  command:  /etc/init.d/mysql stop 

- name: bootstrap node 
  command:  /etc/init.d/mysql bootstrap-pxc 

- name: restart mysql hard
  command: "{{ item }}"
  with_items:
    - /etc/init.d/mysql stop
    - killall mysqld
    - /etc/init.d/mysql start
